# Generated by Django 5.2.4 on 2025-07-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salidas_campo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateField()),
                ('parametro', models.CharField(choices=[('ph', 'pH'), ('turbidez', 'Turbidez'), ('caudal', 'Caudal'), ('otros', 'Otros')], max_length=50)),
                ('valor', models.FloatField()),
                ('unidad', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('salida_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='salidas_campo.salidacampomodel')),
            ],
        ),
    ]
