# Generated by Django 5.2.4 on 2025-07-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuerposagua', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaCampoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('condiciones_climaticas', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuerpo_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_campo', to='cuerposagua.cuerpoaguamodel')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
