# Generated by Django 5.2.4 on 2025-07-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuerpoAguaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('rio', 'Río'), ('laguna', 'Laguna'), ('arroyo', 'Arroyo'), ('otro', 'Otro')], max_length=20)),
                ('ubicacion', models.TextField()),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuerpos_agua', to='localidades.localidadmodel')),
            ],
        ),
    ]
